### ISSUE TITLE
library/math.po üzerinde çalışmak istiyorum.

### ISSUE THREAD

**Issue by berkcangumusisik** [python/python-docs-tr#109]

**Comment by berkcangumusisik** [comment]
Depremin girmesiyle birlikte çok kötü olduğum için unutmuşum 1 hafta içinde tamamlayıp iletiyor olacağım

**Comment by berkcangumusisik** [comment]
Gönderimi tamamladım

**Comment by egeakman** [comment]
> Depremin girmesiyle birlikte çok kötü olduğum için unutmuşum 1 hafta içinde tamamlayıp iletiyor olacağım

Hepimiz zor toparladık 😔 Umarım bir kaybınız olmamıştır. Çeviri için elinize sağlık.
