### ISSUE TITLE
Localde değişiklikleri görmek

### ISSUE THREAD

**Issue by mertssmnoglu** [python/python-docs-tr#118]
Yaptığımız çevirileri localimizde hızlı bir şekilde görmek çok güzel olur. Bunun için bir rehber hazırlanabilir.

- Projeye hız kazandırır.
- Çevirilerimizde bir hata varsa bunları localimizde görüp daha rahat fixleyebiliriz.

**Comment by egeakman** [comment]
Soru için teşekkürler. Birazdan sorduğunuz soruyu da içeren bir SSS oluşturacağım.

**Comment by egeakman** [comment]
Soruyu #119 'da cevapladım. Diğer araçları ve yöntemleri anlatan yazılar da ekleyeceğim.
