### ISSUE TITLE
tutorial/introduction.po üzerinde çalışmak istiyorum.

### ISSUE THREAD

**Issue by yunusolcar** [python/python-docs-tr#175]
Yeni sürümlerle beraber gelen kısımları çevirmek istiyorum.( tutorial/introduction.po)

**Comment by egeakman** [comment]
@yunusolcar Teşekkürler! Dokümanları güncellemem için birkaç gün verebilir misin?

**Comment by yunusolcar** [comment]
> @yunusolcar Teşekkürler! Dokümanları güncellemem için birkaç gün verebilir misin?

Elbette ✅

**Comment by egeakman** [comment]
Güncelleme tamam @yunusolcar
