### ISSUE TITLE
library/time.po üzerinde çalışmak istiyorum.

### ISSUE THREAD

**Issue by serkan-bayram** [python/python-docs-tr#97]

**Comment by serkan-bayram** [comment]
Şu şekilde hatalar alıyorum ve ne olduğunu tam anlayamadım, syntax hataları için library/time.po:1232 tarzında yazan şeylerin nereler olduklarını bulmaya çalıştım ama bulamadım üstünde verdiği hatanın da ne olduğunu bilmiyorum, yardımcı olursanız çok güzel olur teşekkürler.
![image](https://user-images.githubusercontent.com/68502470/220765630-20680393-577a-4d82-8cd5-a5d9a5684b2d.png)

**Comment by egeakman** [comment]
``git add library/time.po`` çalıştırıp tekrar commit etmeyi deneyebilir misiniz? Sonrasında yine olmazsa ``no-verify`` flag'iyle commit ederseniz github üzerinde gösterebilirim nerede hata olduğunu.
